Output_Directory:
  outputs
Input_Directory:
  data
Sample_Sheet:
  data/samplesheet_Cong.csv
Adapter:
  data/TruSeqAdapt.fa
Genome:
  data/genome/homo_dna.fasta
Genes_signature: # marker based signature for MCPCounter ONLY
  data/signature/genes.txt
Signature: # regular signature for deconRNAseq
  data/signature/TIL10.txt
GTF: # must be full path for R
  /home/julien/Documents/lungProject/data/genome/homo.gtf.gz
THREADS: 
  12
Trim_with: # Trimmomatic or Trimgalore
  Trimmomatic
Quantification_with: # kallisto or salmon or STAR
  kallisto
Index_kallisto:
  data/genome/transcript.idx
Index_salmon:
  data/genome/salmon_index
Index_STAR:
  data/star
Convert_bcl2fastq: # yes or no, don't forget the ""
  "no"
Deconvolution_method: # quantiseq, deconRNAseq or mcpcounter
  quantiseq
Do_deconv: # yes or no, don't forget the ""
  "yes"
Do_rnaseq: # yes or no, don't forget the ""
  "yes"
Samples:
  data/samples.txt