# General info
Output_Directory:
  outputs
Input_Directory: # location of your data
  /home/julien/Documents/pipeline_rnaseq/outputs/Quantification/all_sample_quantified_LP.txt
 # /mnt/SERVER-CRCT-STORAGE/CRCT21/Private/Common/DNA_WGBS_methylation/blueprint_data.txt
THREADS: # number of threads to use
  14
Sample_Sheet:
  data/samplesheet_Cong.csv
Adapter: # illumina adapter
  data/TruSeqAdapt.fa
Samples: # link to file containing the list of samples / conditions
  data/samples.txt

# Options
Trim_with: # Trimmomatic or Trimgalore
  Trimmomatic
Do_deconv: # run the deconvolution ? "yes" or "no", don't forget the ""
  "no"
Do_rnaseq: # run the rna-seq pipeline ? "yes" or "no", don't forget the ""
  "yes"
Convert_bcl2fastq: # Do you need to convert from raw illumina bcl to fastq ?  "yes" or "no", don't forget the ""
  "no"
Need_merging: #if above condition is no, then do you need to merge experimental lanes into one file ?
  "no"

# Quantification
Quantification_with: # kallisto or salmon or STAR
  STAR
Index_rnaseq: # kallisto or Salmon ndex file location
  data/genome/transcript.idx

# Deconvolution
Genes_signature: # marker based signature for MCPCounter ONLY
  data/signature/genes.txt
Signature: # regular signature for deconRNAseq and epidish
  /mnt/SERVER-CRCT-STORAGE/CRCT21/Private/Common/DNA_WGBS_methylation/signature/BPRNACan+.tsv
Deconvolution_method: # quantiseq, deconRNAseq, epidish or mcpcounter
  epidish


################################# STAR specific files ###############
GTF: # must be full path for R, also not zipped
  /home/julien/Documents/pipeline_rnaseq/data/genome/homo_grch38.gtf
Genome: # 
  data/genome/homo_grch38_dna.fasta
Index_STAR: # STAR index files location
  data/star