# General info
Output_Directory:
  outputs
Input: # location of your data
  input_test
THREADS: # number of threads to use
  14

# Rnaseq quantification option
Do_rnaseq: # run the rna-seq pipeline ? "yes" or "no", don't forget the ""
  "yes"
Samples: # link to file containing the list of samples name
  data/samples.txt

# Conversion BCL to FASTQ format
Convert_bcl2fastq: # Do you need to convert from raw illumina bcl to fastq ?  "yes" or "no", don't forget the ""
  "no"
Sample_Sheet:
  data/SampleSheetCLL-1.csv

# Trimming process
Trim_with: # Trimmomatic or Trimgalore
  Trimmomatic
Adapter: # illumina adapter
  data/TruSeqAdapt.fa
Quantification_with: # STAR or kallisto or salmon
  STAR
Index_rnaseq: # path to kallisto Index file location or Salmon or STAR 2.7.6a Index folder location
   

# If you can't provide the index :
Compute_index:
  "yes"
CDNA: # Required for Salmon and Kallisto
  data/genome/homo_grch38_cdna.fa.gz
  # Computing indexes requires the 2 following files. They are also required if you chose to run STAR+RSEM
GTF: # If STAR method is chosen. Path to the GTF file. Not a zipped format
  data/genome/homo_grch38.gtf
Genome: # If STAR method is chosen. Path to the reference genome sequence. It must be fasta format.
  data/genome/homo_grch38_dna.fasta

# Deconvolution option
Do_deconv: # run the deconvolution ? "yes" or "no", don't forget the ""
  "no"

Signatures:
  data/signatures

