Samples: 
  Test-Cong-A
Output_Directory:
  outputs
Input_Directory:
  data
Sample_Sheet:
  data/samplesheet_Cong.csv
Adapter:
  data/TruSeqAdapt.fa
Genome:
  data/genome/homo_dna.fasta
GTF: # must be full path for R
  /home/julien/Documents/lungProject/data/genome/homo.gtf.gz
THREADS: 
  12
Trim_with: # Trimmomatic or Trimgalore
  Trimmomatic
Quantification_with: # kallisto or salmon or STAR
  kallisto
Index_kallisto:
  data/genome/transcript.idx
Index_salmon:
  data/genome/salmon_index
Index_STAR:
  data/star
Convert_bcl2fastq: # yes or no
  "no"
