# General info
Output_Directory:
  ../outputs
Input: # location of your data
  /home/julien/Documents/testou
THREADS: # number of threads to use
  14

# Conversion BCL to FASTQ format
Convert_bcl2fastq: # Do you need to convert from raw illumina bcl to fastq ?  "yes" or "no", don't forget the ""
  "no"
Sample_Sheet:
  /home/julien/Documents/data/Eq9_and_21/SampleSheetCLL-1.csv

# Rnaseq quantification option
Do_rnaseq: # run the rna-seq pipeline ? "yes" or "no", don't forget the ""
  "yes"
Samples: # link to file containing the list of samples name
  ../samples.txt

# Trimming process
Trim_with: # Trimmomatic or Trimgalore
  Trimmomatic
Adapter: # illumina adapter
  /home/julien/Documents/pipeline_rnaseq/data/TruSeqAdapt.fa
Quantification_with: # STAR or kallisto or salmon
  salmon
Index_rnaseq: # path to kallisto Index file location or Salmon or STAR 2.7.6a Index folder location
  /path/to/index/

# If you can't provide the index :
Compute_index:
  "yes"
CDNA: # Required for Salmon and Kallisto
  /home/julien/Documents/pipeline_rnaseq/data/genome/homo_grch38_cdna.fa.gz
  # Computing indexes requires the 2 following files. They are
Genome: # Path to the reference genome sequence. It must be fasta format. Required for Salmon and STAR
  /home/julien/Documents/pipeline_rnaseq/data/genome/homo_grch38_dna.fasta
GTF: # Path to the GTF file. Not a zipped format.  Required if you chose to run STAR+RSEM
  /home/julien/Documents/pipeline_rnaseq/data/genome/homo_grch38.gtf

# Deconvolution option
Do_deconv: # run the deconvolution ? "yes" or "no", don't forget the ""
  "no"
Signatures:
  data/signatures