Output_Directory:
  outputs
Input_Directory: # location of your data
  /home/julien/Documents/lungProject/outputs/bcl2raw
Sample_Sheet:
  data/samplesheet_Cong.csv
Adapter: # illumina adapter
  data/TruSeqAdapt.fa
Genome:
  data/genome/homo_dna.fasta
Genes_signature: # marker based signature for MCPCounter ONLY
  data/signature/genes.txt
Signature: # regular signature for deconRNAseq
  data/signature/TIL10.txt
GTF: # must be full path for R
  /home/julien/Documents/lungProject/data/genome/homo.gtf.gz
THREADS: 
  12
Trim_with: # Trimmomatic or Trimgalore
  Trimmomatic
Quantification_with: # kallisto or salmon or STAR
  kallisto
Index_kallisto: # kallisto index file location
  data/genome/transcript.idx
Index_salmon: # salmon index files location
  data/genome/salmon_index
Index_STAR: # STAR index files location
  data/star
Convert_bcl2fastq: # Do you need to convert from raw illumina bcl to fastq ?  "yes" or "no", don't forget the ""
  "no"
Need_merging: #if above condition is no, then do you need to merge experimental lanes into one file ?
  "yes"
Deconvolution_method: # quantiseq, deconRNAseq or mcpcounter
  quantiseq
Do_deconv: # run the deconvolution ? "yes" or "no", don't forget the ""
  "no"
Do_rnaseq: # run the rna-seq pipeline ? "yes" or "no", don't forget the ""
  "yes"
Samples: # link to file containing the list of samples / conditions
  data/samples.txt